// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrh-BGh8Q6l3xzW1Cl4233qSVLMzYQWc',
    appId: '1:293645725334:web:1141dc1d6d7aaea7f61cb7',
    messagingSenderId: '293645725334',
    projectId: 'whatsappclone-c6d2b',
    authDomain: 'whatsappclone-c6d2b.firebaseapp.com',
    storageBucket: 'whatsappclone-c6d2b.appspot.com',
    measurementId: 'G-RBQVLF5JCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeml-MByiwzTZ0RgbheJ2TQZtf5KGGcmU',
    appId: '1:293645725334:android:57ba6b4dc1b97c27f61cb7',
    messagingSenderId: '293645725334',
    projectId: 'whatsappclone-c6d2b',
    storageBucket: 'whatsappclone-c6d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJfK87dKTMzr6wtV7kJ-Vu3ZT6X5Q6VI',
    appId: '1:293645725334:ios:1c73a0e4bbe30daef61cb7',
    messagingSenderId: '293645725334',
    projectId: 'whatsappclone-c6d2b',
    storageBucket: 'whatsappclone-c6d2b.appspot.com',
    iosClientId: '293645725334-hg5jgvbbfo2vo3807o1pt30o0qqcmobt.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatasappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJfK87dKTMzr6wtV7kJ-Vu3ZT6X5Q6VI',
    appId: '1:293645725334:ios:1c73a0e4bbe30daef61cb7',
    messagingSenderId: '293645725334',
    projectId: 'whatsappclone-c6d2b',
    storageBucket: 'whatsappclone-c6d2b.appspot.com',
    iosClientId: '293645725334-hg5jgvbbfo2vo3807o1pt30o0qqcmobt.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatasappClone',
  );
}
